server:
  port: 8763
spring:
  application:
    name: microservice-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000