server:
  port: 8762
spring:
  application:
    name: microservice-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#feign客户端启动hystrix断路保护
feign:
  hystrix:
    enabled: true


ribbon:
  ReadTimeout: 120000  #处理超时时间 默认5秒
  ConnectTimeout: 120000 #连接超时时间 默认2秒


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000 #断路切换超时
